// 初期単語データの定義と投入処理
import { createAdminClient } from "@/lib/supabase-admin";

const TOEIC_600_WORDS = [
  // ... existing words ...
  // Business (35 words)
  {
    word: "schedule",
    meaning: "スケジュール、予定",
    pronunciation: "/ˈskedʒ.uːl/",
    part_of_speech: "noun",
    example_sentence: "Please check your schedule for next week.",
    difficulty: "intermediate",
    category: "business",
  },
  {
    word: "deadline",
    meaning: "締め切り、期限",
    pronunciation: "/ˈded.laɪn/",
    part_of_speech: "noun",
    example_sentence: "The deadline for this project is Friday.",
    difficulty: "intermediate",
    category: "business",
  },
  {
    word: "budget",
    meaning: "予算",
    pronunciation: "/ˈbʌdʒ.ɪt/",
    part_of_speech: "noun",
    example_sentence: "We need to stay within the budget.",
    difficulty: "intermediate",
    category: "business",
  },
  {
    word: "colleague",
    meaning: "同僚",
    pronunciation: "/ˈkɒl.iːɡ/",
    part_of_speech: "noun",
    example_sentence: "My colleague helped me with the report.",
    difficulty: "intermediate",
    category: "business",
  },
  {
    word: "department",
    meaning: "部門、部署",
    pronunciation: "/dɪˈpɑːt.mənt/",
    part_of_speech: "noun",
    example_sentence: "Which department do you work in?",
    difficulty: "intermediate",
    category: "business",
  },
  {
    word: "employee",
    meaning: "従業員、社員",
    pronunciation: "/ɪmˈplɔɪ.iː/",
    part_of_speech: "noun",
    example_sentence: "The company has 500 employees.",
    difficulty: "intermediate",
    category: "business",
  },
  {
    word: "contract",
    meaning: "契約",
    pronunciation: "/ˈkɒn.trækt/",
    part_of_speech: "noun",
    example_sentence: "Please review the contract carefully.",
    difficulty: "intermediate",
    category: "business",
  },
  {
    word: "invoice",
    meaning: "請求書",
    pronunciation: "/ˈɪn.vɔɪs/",
    part_of_speech: "noun",
    example_sentence: "I will send you the invoice tomorrow.",
    difficulty: "intermediate",
    category: "business",
  },
  {
    word: "profit",
    meaning: "利益",
    pronunciation: "/ˈprɒf.ɪt/",
    part_of_speech: "noun",
    example_sentence: "The company made a good profit this year.",
    difficulty: "intermediate",
    category: "business",
  },
  {
    word: "salary",
    meaning: "給料",
    pronunciation: "/ˈsæl.ər.i/",
    part_of_speech: "noun",
    example_sentence: "My salary is paid monthly.",
    difficulty: "intermediate",
    category: "business",
  },
  {
    word: "negotiate",
    meaning: "交渉する",
    pronunciation: "/nəˈɡəʊ.ʃi.eɪt/",
    part_of_speech: "verb",
    example_sentence: "We need to negotiate the price.",
    difficulty: "intermediate",
    category: "business",
  },
  {
    word: "agreement",
    meaning: "合意、契約",
    pronunciation: "/əˈɡriː.mənt/",
    part_of_speech: "noun",
    example_sentence: "We reached an agreement yesterday.",
    difficulty: "intermediate",
    category: "business",
  },
  {
    word: "strategy",
    meaning: "戦略",
    pronunciation: "/ˈstræt.ə.dʒi/",
    part_of_speech: "noun",
    example_sentence: "We need a new marketing strategy.",
    difficulty: "intermediate",
    category: "business",
  },
  {
    word: "expansion",
    meaning: "拡大",
    pronunciation: "/ɪkˈspæn.ʃən/",
    part_of_speech: "noun",
    example_sentence: "The company is planning an international expansion.",
    difficulty: "intermediate",
    category: "business",
  },
  {
    word: "benefit",
    meaning: "利益、恩恵",
    pronunciation: "/ˈben.ɪ.fɪt/",
    part_of_speech: "noun",
    example_sentence: "This new system will benefit everyone.",
    difficulty: "intermediate",
    category: "business",
  },
  {
    word: "promotion",
    meaning: "昇進、促進",
    pronunciation: "/prəˈməʊ.ʃən/",
    part_of_speech: "noun",
    example_sentence: "Congratulations on your promotion!",
    difficulty: "intermediate",
    category: "business",
  },
  {
    word: "advertise",
    meaning: "宣伝する",
    pronunciation: "/ˈæd.və.taɪz/",
    part_of_speech: "verb",
    example_sentence: "We need to advertise our new product.",
    difficulty: "intermediate",
    category: "business",
  },
  {
    word: "headquarters",
    meaning: "本社",
    pronunciation: "/ˌhedˈkwɔː.təz/",
    part_of_speech: "noun",
    example_sentence: "Our headquarters are located in Tokyo.",
    difficulty: "intermediate",
    category: "business",
  },
  {
    word: "logistics",
    meaning: "物流",
    pronunciation: "/ləˈdʒɪs.tɪks/",
    part_of_speech: "noun",
    example_sentence: "The logistics of the event are complex.",
    difficulty: "intermediate",
    category: "business",
  },
  {
    word: "personnel",
    meaning: "人員、職員",
    pronunciation: "/ˌpɜː.sənˈel/",
    part_of_speech: "noun",
    example_sentence: "The personnel department is on the second floor.",
    difficulty: "intermediate",
    category: "business",
  },
  {
    word: "signature",
    meaning: "署名",
    pronunciation: "/ˈsɪɡ.nə.tʃə/",
    part_of_speech: "noun",
    example_sentence: "We need your signature on this form.",
    difficulty: "intermediate",
    category: "business",
  },
  {
    word: "representative",
    meaning: "代表者、担当者",
    pronunciation: "/ˌrep.rɪˈzen.tə.tɪv/",
    part_of_speech: "noun",
    example_sentence: "A sales representative will call you shortly.",
    difficulty: "intermediate",
    category: "business",
  },
  {
    word: "appointment",
    meaning: "予約",
    pronunciation: "/əˈpɔɪnt.mənt/",
    part_of_speech: "noun",
    example_sentence: "I have an appointment at 3 PM.",
    difficulty: "intermediate",
    category: "business",
  },
  {
    word: "equipment",
    meaning: "設備、機器",
    pronunciation: "/ɪˈkwɪp.mənt/",
    part_of_speech: "noun",
    example_sentence: "The office needs new computer equipment.",
    difficulty: "intermediate",
    category: "business",
  },
  {
    word: "guarantee",
    meaning: "保証",
    pronunciation: "/ˌɡær.ənˈtiː/",
    part_of_speech: "noun/verb",
    example_sentence: "This product comes with a two-year guarantee.",
    difficulty: "intermediate",
    category: "business",
  },
  {
    word: "invest",
    meaning: "投資する",
    pronunciation: "/ɪnˈvest/",
    part_of_speech: "verb",
    example_sentence: "It is a good time to invest in technology.",
    difficulty: "intermediate",
    category: "business",
  },
  {
    word: "merger",
    meaning: "合併",
    pronunciation: "/ˈmɜː.dʒə/",
    part_of_speech: "noun",
    example_sentence: "The merger of the two companies was successful.",
    difficulty: "advanced",
    category: "business",
  },
  {
    word: "policy",
    meaning: "方針、政策",
    pronunciation: "/ˈpɒl.ə.si/",
    part_of_speech: "noun",
    example_sentence: "Please read our company policy on remote work.",
    difficulty: "intermediate",
    category: "business",
  },
  {
    word: "quarter",
    meaning: "四半期",
    pronunciation: "/ˈkwɔː.tə/",
    part_of_speech: "noun",
    example_sentence: "Sales increased in the third quarter.",
    difficulty: "intermediate",
    category: "business",
  },
  {
    word: "recruit",
    meaning: "採用する",
    pronunciation: "/rɪˈkruːt/",
    part_of_speech: "verb",
    example_sentence: "We need to recruit more experienced engineers.",
    difficulty: "intermediate",
    category: "business",
  },
  {
    word: "redundant",
    meaning: "余剰の、解雇された",
    pronunciation: "/rɪˈdʌn.dənt/",
    part_of_speech: "adj",
    example_sentence: "New technology has made many jobs redundant.",
    difficulty: "advanced",
    category: "business",
  },
  {
    word: "supervise",
    meaning: "監督する",
    pronunciation: "/ˈsuː.pə.vaɪz/",
    part_of_speech: "verb",
    example_sentence: "She supervises a team of ten people.",
    difficulty: "intermediate",
    category: "business",
  },
  {
    word: "undergo",
    meaning: "経験する、受ける",
    pronunciation: "/ˌʌn.dəˈɡəʊ/",
    part_of_speech: "verb",
    example_sentence: "The factory is undergoing a major renovation.",
    difficulty: "advanced",
    category: "business",
  },
  {
    word: "vendor",
    meaning: "販売業者",
    pronunciation: "/ˈven.də/",
    part_of_speech: "noun",
    example_sentence: "We need to find a new software vendor.",
    difficulty: "intermediate",
    category: "business",
  },
  {
    word: "warehouse",
    meaning: "倉庫",
    pronunciation: "/ˈweə.haʊs/",
    part_of_speech: "noun",
    example_sentence: "The stock is kept in a large warehouse.",
    difficulty: "intermediate",
    category: "business",
  },

  // Daily Life (35 words)
  {
    word: "neighborhood",
    meaning: "近所、地域",
    pronunciation: "/ˈneɪ.bə.hʊd/",
    part_of_speech: "noun",
    example_sentence: "This is a quiet neighborhood.",
    difficulty: "intermediate",
    category: "daily",
  },
  {
    word: "pharmacy",
    meaning: "薬局",
    pronunciation: "/ˈfɑː.mə.si/",
    part_of_speech: "noun",
    example_sentence: "You can buy medicine at the pharmacy.",
    difficulty: "intermediate",
    category: "daily",
  },
  {
    word: "transportation",
    meaning: "交通機関",
    pronunciation: "/ˌtræn.spɔːˈteɪ.ʃən/",
    part_of_speech: "noun",
    example_sentence: "Public transportation is convenient here.",
    difficulty: "intermediate",
    category: "daily",
  },
  {
    word: "reservation",
    meaning: "予約",
    pronunciation: "/ˌrez.əˈveɪ.ʃən/",
    part_of_speech: "noun",
    example_sentence: "I made a reservation for two people.",
    difficulty: "intermediate",
    category: "daily",
  },
  {
    word: "receipt",
    meaning: "領収書",
    pronunciation: "/rɪˈsiːt/",
    part_of_speech: "noun",
    example_sentence: "Can I have a receipt, please?",
    difficulty: "intermediate",
    category: "daily",
  },
  {
    word: "discount",
    meaning: "割引",
    pronunciation: "/ˈdɪs.kaʊnt/",
    part_of_speech: "noun",
    example_sentence: "There is a 20% discount today.",
    difficulty: "intermediate",
    category: "daily",
  },
  {
    word: "delivery",
    meaning: "配達",
    pronunciation: "/dɪˈlɪv.ər.i/",
    part_of_speech: "noun",
    example_sentence: "The delivery will arrive tomorrow.",
    difficulty: "intermediate",
    category: "daily",
  },
  {
    word: "complaint",
    meaning: "苦情",
    pronunciation: "/kəmˈpleɪnt/",
    part_of_speech: "noun",
    example_sentence: "I want to make a complaint about the service.",
    difficulty: "intermediate",
    category: "daily",
  },
  {
    word: "recommend",
    meaning: "推薦する",
    pronunciation: "/ˌrek.əˈmend/",
    part_of_speech: "verb",
    example_sentence: "Can you recommend a good hotel?",
    difficulty: "intermediate",
    category: "daily",
  },
  {
    word: "available",
    meaning: "利用可能な",
    pronunciation: "/əˈveɪ.lə.bəl/",
    part_of_speech: "adj",
    example_sentence: "Is this table available?",
    difficulty: "intermediate",
    category: "daily",
  },
  {
    word: "convenient",
    meaning: "便利な",
    pronunciation: "/kənˈviː.ni.ənt/",
    part_of_speech: "adj",
    example_sentence: "This location is very convenient.",
    difficulty: "intermediate",
    category: "daily",
  },
  {
    word: "crowded",
    meaning: "混雑した",
    pronunciation: "/ˈkraʊ.dɪd/",
    part_of_speech: "adj",
    example_sentence: "The train was crowded this morning.",
    difficulty: "intermediate",
    category: "daily",
  },
  {
    word: "expensive",
    meaning: "高価な",
    pronunciation: "/ɪkˈspen.sɪv/",
    part_of_speech: "adj",
    example_sentence: "This restaurant is too expensive.",
    difficulty: "beginner",
    category: "daily",
  },
  {
    word: "environment",
    meaning: "環境",
    pronunciation: "/ɪnˈvaɪ.rən.mənt/",
    part_of_speech: "noun",
    example_sentence: "We should protect the environment.",
    difficulty: "intermediate",
    category: "daily",
  },
  {
    word: "community",
    meaning: "共同体、地域社会",
    pronunciation: "/kəˈmjuː.nə.ti/",
    part_of_speech: "noun",
    example_sentence: "He is active in the local community.",
    difficulty: "intermediate",
    category: "daily",
  },
  {
    word: "agriculture",
    meaning: "農業",
    pronunciation: "/ˈæɡ.rɪ.kʌl.tʃə/",
    part_of_speech: "noun",
    example_sentence: "Agriculture is the main industry in this region.",
    difficulty: "intermediate",
    category: "daily",
  },
  {
    word: "appliance",
    meaning: "家電製品",
    pronunciation: "/əˈplaɪ.əns/",
    part_of_speech: "noun",
    example_sentence: "The kitchen is equipped with modern appliances.",
    difficulty: "intermediate",
    category: "daily",
  },
  {
    word: "commute",
    meaning: "通勤する",
    pronunciation: "/kəˈmjuːt/",
    part_of_speech: "verb",
    example_sentence: "I commute to Tokyo every day by train.",
    difficulty: "intermediate",
    category: "daily",
  },
  {
    word: "diet",
    meaning: "食事、ダイエット",
    pronunciation: "/ˈdaɪ.ət/",
    part_of_speech: "noun",
    example_sentence: "A balanced diet is important for health.",
    difficulty: "beginner",
    category: "daily",
  },
  {
    word: "furniture",
    meaning: "家具",
    pronunciation: "/ˈfɜː.nɪ.tʃə/",
    part_of_speech: "noun",
    example_sentence: "We bought some new furniture for the living room.",
    difficulty: "beginner",
    category: "daily",
  },
  {
    word: "infrastructure",
    meaning: "インフラ、基盤",
    pronunciation: "/ˈɪn.frəˌstrʌk.tʃə/",
    part_of_speech: "noun",
    example_sentence: "The city needs better infrastructure.",
    difficulty: "advanced",
    category: "daily",
  },
  {
    word: "maintenance",
    meaning: "保守、維持",
    pronunciation: "/ˈmeɪn.tən.əns/",
    part_of_speech: "noun",
    example_sentence: "The car needs regular maintenance.",
    difficulty: "intermediate",
    category: "daily",
  },
  {
    word: "nutrition",
    meaning: "栄養",
    pronunciation: "/njuːˈtrɪʃ.ən/",
    part_of_speech: "noun",
    example_sentence: "Good nutrition is essential for growth.",
    difficulty: "intermediate",
    category: "daily",
  },
  {
    word: "renovation",
    meaning: "改修、リフォーム",
    pronunciation: "/ˌren.əˈveɪ.ʃən/",
    part_of_speech: "noun",
    example_sentence: "The house is under renovation.",
    difficulty: "intermediate",
    category: "daily",
  },
  {
    word: "sustainable",
    meaning: "持続可能な",
    pronunciation: "/səˈsteɪ.nə.bəl/",
    part_of_speech: "adj",
    example_sentence: "We need to find sustainable energy sources.",
    difficulty: "intermediate",
    category: "daily",
  },
  {
    word: "utility",
    meaning: "公共料金、有用性",
    pronunciation: "/juːˈtɪl.ə.ti/",
    part_of_speech: "noun",
    example_sentence: "The rent includes utility bills.",
    difficulty: "intermediate",
    category: "daily",
  },
  {
    word: "volunteer",
    meaning: "ボランティア",
    pronunciation: "/ˌvɒl.ənˈtɪə/",
    part_of_speech: "noun/verb",
    example_sentence: "She works as a volunteer at the hospital.",
    difficulty: "intermediate",
    category: "daily",
  },
  {
    word: "waste",
    meaning: "無駄、廃棄物",
    pronunciation: "/weɪst/",
    part_of_speech: "noun/verb",
    example_sentence: "Don't waste your time.",
    difficulty: "beginner",
    category: "daily",
  },
  {
    word: "welfare",
    meaning: "福祉",
    pronunciation: "/ˈwel.feə/",
    part_of_speech: "noun",
    example_sentence: "The government is responsible for public welfare.",
    difficulty: "intermediate",
    category: "daily",
  },
  {
    word: "atmosphere",
    meaning: "雰囲気、大気",
    pronunciation: "/ˈæt.mə.sfɪə/",
    part_of_speech: "noun",
    example_sentence: "The restaurant has a friendly atmosphere.",
    difficulty: "intermediate",
    category: "daily",
  },
  {
    word: "beverage",
    meaning: "飲料",
    pronunciation: "/ˈbev.ər.ɪdʒ/",
    part_of_speech: "noun",
    example_sentence: "Alcoholic beverages are not served here.",
    difficulty: "intermediate",
    category: "daily",
  },
  {
    word: "chore",
    pronunciation: "/tʃɔː/",
    meaning: "雑用、家事",
    part_of_speech: "noun",
    example_sentence: "Household chores can be time-consuming.",
    difficulty: "intermediate",
    category: "daily",
  },
  {
    word: "ingredient",
    meaning: "材料",
    pronunciation: "/ɪnˈɡriː.di.ənt/",
    part_of_speech: "noun",
    example_sentence: "Fresh ingredients are key to good cooking.",
    difficulty: "intermediate",
    category: "daily",
  },
  {
    word: "leisure",
    meaning: "余暇",
    pronunciation: "/ˈleʒ.ə/",
    part_of_speech: "noun",
    example_sentence: "What do you do in your leisure time?",
    difficulty: "intermediate",
    category: "daily",
  },
  {
    word: "recreation",
    meaning: "娯楽",
    pronunciation: "/ˌrek.riˈeɪ.ʃən/",
    part_of_speech: "noun",
    example_sentence: "The park is a popular place for recreation.",
    difficulty: "intermediate",
    category: "daily",
  },

  // Travel & Others (30 words)
  {
    word: "accommodation",
    meaning: "宿泊施設",
    pronunciation: "/əˌkɒm.əˈdeɪ.ʃən/",
    part_of_speech: "noun",
    example_sentence: "We need to book accommodation.",
    difficulty: "advanced",
    category: "travel",
  },
  {
    word: "souvenir",
    meaning: "お土産",
    pronunciation: "/ˌsuː.vəˈnɪə/",
    part_of_speech: "noun",
    example_sentence: "I bought some souvenirs.",
    difficulty: "intermediate",
    category: "travel",
  },
  {
    word: "customs",
    meaning: "税関",
    pronunciation: "/ˈkʌs.təmz/",
    part_of_speech: "noun",
    example_sentence: "You need to go through customs.",
    difficulty: "intermediate",
    category: "travel",
  },
  {
    word: "departure",
    meaning: "出発",
    pronunciation: "/dɪˈpɑː.tʃə/",
    part_of_speech: "noun",
    example_sentence: "The departure time is 9 AM.",
    difficulty: "intermediate",
    category: "travel",
  },
  {
    word: "arrival",
    meaning: "到着",
    pronunciation: "/əˈraɪ.vəl/",
    part_of_speech: "noun",
    example_sentence: "The arrival time is 3 PM.",
    difficulty: "intermediate",
    category: "travel",
  },
  {
    word: "itinerary",
    meaning: "旅程",
    pronunciation: "/aɪˈtɪn.ər.ər.i/",
    part_of_speech: "noun",
    example_sentence: "We followed a strict itinerary during the trip.",
    difficulty: "advanced",
    category: "travel",
  },
  {
    word: "baggage",
    meaning: "荷物",
    pronunciation: "/ˈbæɡ.ɪdʒ/",
    part_of_speech: "noun",
    example_sentence: "Excess baggage fees can be quite high.",
    difficulty: "intermediate",
    category: "travel",
  },
  {
    word: "boarding",
    meaning: "搭乗",
    pronunciation: "/ˈbɔː.dɪŋ/",
    part_of_speech: "noun",
    example_sentence: "Boarding will start in 15 minutes.",
    difficulty: "intermediate",
    category: "travel",
  },
  {
    word: "concierge",
    meaning: "コンシェルジュ",
    pronunciation: "/ˌkɒn.siˈeəʒ/",
    part_of_speech: "noun",
    example_sentence: "The hotel concierge can help you book tickets.",
    difficulty: "advanced",
    category: "travel",
  },
  {
    word: "confirmation",
    meaning: "確認",
    pronunciation: "/ˌkɒn.fəˈmeɪ.ʃən/",
    part_of_speech: "noun",
    example_sentence: "Did you receive a confirmation email?",
    difficulty: "intermediate",
    category: "travel",
  },
  {
    word: "currency",
    meaning: "通貨",
    pronunciation: "/ˈkʌr.ən.si/",
    part_of_speech: "noun",
    example_sentence: "You can exchange currency at the airport.",
    difficulty: "intermediate",
    category: "travel",
  },
  {
    word: "embark",
    meaning: "乗船する、着手する",
    pronunciation: "/ɪmˈbɑːk/",
    part_of_speech: "verb",
    example_sentence: "Passengers are ready to embark on the ship.",
    difficulty: "advanced",
    category: "travel",
  },
  {
    word: "expedition",
    meaning: "遠征、探検",
    pronunciation: "/ˌek.spəˈdɪʃ.ən/",
    part_of_speech: "noun",
    example_sentence: "The scientific expedition lasted for three months.",
    difficulty: "advanced",
    category: "travel",
  },
  {
    word: "hospitality",
    meaning: "おもてなし",
    pronunciation: "/ˌhɒs.pɪˈtæl.ə.ti/",
    part_of_speech: "noun",
    example_sentence: "Thank you for your warm hospitality.",
    difficulty: "intermediate",
    category: "travel",
  },
  {
    word: "landmark",
    meaning: "目印、名所",
    pronunciation: "/ˈlænd.mɑːk/",
    part_of_speech: "noun",
    example_sentence: "The Statue of Liberty is a famous landmark.",
    difficulty: "intermediate",
    category: "travel",
  },
  {
    word: "passenger",
    meaning: "乗客",
    pronunciation: "/ˈpæs.ən.dʒə/",
    part_of_speech: "noun",
    example_sentence: "All passengers must remain seated.",
    difficulty: "beginner",
    category: "travel",
  },
  {
    word: "scenic",
    meaning: "景色の良い",
    pronunciation: "/ˈsiː.nɪk/",
    part_of_speech: "adj",
    example_sentence: "We took a scenic route through the mountains.",
    difficulty: "intermediate",
    category: "travel",
  },
  {
    word: "transit",
    meaning: "通過、乗り継ぎ",
    pronunciation: "/ˈtræn.zɪt/",
    part_of_speech: "noun",
    example_sentence: "He is in transit at Dubai airport.",
    difficulty: "intermediate",
    category: "travel",
  },
  {
    word: "vacancy",
    meaning: "空室",
    pronunciation: "/ˈveɪ.kən.si/",
    part_of_speech: "noun",
    example_sentence: 'The hotel has a "No Vacancy" sign.',
    difficulty: "intermediate",
    category: "travel",
  },
  {
    word: "visa",
    meaning: "ビザ",
    pronunciation: "/ˈviː.zə/",
    part_of_speech: "noun",
    example_sentence: "You need a visa to enter the country.",
    difficulty: "beginner",
    category: "travel",
  },
  {
    word: "voyage",
    meaning: "航海、船旅",
    pronunciation: "/ˈvɔɪ.ɪdʒ/",
    part_of_speech: "noun",
    example_sentence: "The voyage across the Atlantic took two weeks.",
    difficulty: "intermediate",
    category: "travel",
  },
  {
    word: "abroad",
    meaning: "海外で",
    pronunciation: "/əˈbrɔːd/",
    part_of_speech: "adv",
    example_sentence: "I would like to study abroad.",
    difficulty: "beginner",
    category: "travel",
  },
  {
    word: "destination",
    meaning: "目的地",
    pronunciation: "/ˌdes.tɪˈneɪ.ʃən/",
    part_of_speech: "noun",
    example_sentence: "What is your final destination?",
    difficulty: "intermediate",
    category: "travel",
  },
  {
    word: "excursion",
    meaning: "小旅行、遠足",
    pronunciation: "/ɪkˈskɜː.ʃən/",
    part_of_speech: "noun",
    example_sentence: "We went on a day excursion to the island.",
    difficulty: "advanced",
    category: "travel",
  },
  {
    word: "sightseeing",
    meaning: "観光",
    pronunciation: "/ˈsaɪtˌsiː.ɪŋ/",
    part_of_speech: "noun",
    example_sentence: "We did a lot of sightseeing in Paris.",
    difficulty: "intermediate",
    category: "travel",
  },
  {
    word: "transport",
    meaning: "輸送する",
    pronunciation: "/ˈtræn.spɔːt/",
    part_of_speech: "noun/verb",
    example_sentence: "The goods were transported by truck.",
    difficulty: "intermediate",
    category: "travel",
  },
  {
    word: "agency",
    meaning: "代理店",
    pronunciation: "/ˈeɪ.dʒən.si/",
    part_of_speech: "noun",
    example_sentence: "We booked the trip through a travel agency.",
    difficulty: "intermediate",
    category: "travel",
  },
  {
    word: "charter",
    meaning: "貸し切る",
    pronunciation: "/ˈtʃɑː.tə/",
    part_of_speech: "verb/noun",
    example_sentence: "They chartered a private jet.",
    difficulty: "advanced",
    category: "travel",
  },
  {
    word: "ferry",
    meaning: "フェリー",
    pronunciation: "/ˈfer.i/",
    part_of_speech: "noun",
    example_sentence: "We took the ferry across the river.",
    difficulty: "beginner",
    category: "travel",
  },
  {
    word: "resort",
    meaning: "リゾート",
    pronunciation: "/rɪˈzɔːt/",
    part_of_speech: "noun",
    example_sentence: "The beach resort was beautiful.",
    difficulty: "beginner",
    category: "travel",
  },
];

export async function seedWords() {
  const supabase = createAdminClient();

  console.log("🗑️ Deleting old words...");
  await supabase.from("words").delete().neq("id", 0);

  console.log(`📝 Inserting ${TOEIC_600_WORDS.length} TOEIC 600 words...`);

  const { error } = await supabase.from("words").insert(TOEIC_600_WORDS);

  if (error) {
    console.error("Error seeding words:", error);
  } else {
    console.log("✅ Words seeded successfully!");
  }
}
