-- プロフィールテーブル (auth.usersと連携)
CREATE TABLE profiles (
  id UUID REFERENCES auth.users ON DELETE CASCADE PRIMARY KEY,
  full_name TEXT,
  avatar_url TEXT,
  role TEXT DEFAULT 'user' CHECK (role IN ('user', 'admin')),
  stripe_customer_id TEXT,
  subscription_status TEXT DEFAULT 'free' CHECK (subscription_status IN ('free', 'active', 'canceled', 'past_due')),
  created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- 単語テーブル
CREATE TYPE difficulty_level AS ENUM ('beginner', 'intermediate', 'advanced');

CREATE TABLE words (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  word TEXT NOT NULL UNIQUE,
  meaning TEXT NOT NULL,
  pronunciation TEXT,
  part_of_speech TEXT,
  example_sentence TEXT,
  difficulty difficulty_level DEFAULT 'beginner' NOT NULL,
  category TEXT,
  image_url TEXT,
  audio_url TEXT,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- 学習進捗テーブル
CREATE TYPE learning_status AS ENUM ('new', 'learning', 'reviewing', 'mastered');

CREATE TABLE user_word_progress (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id UUID REFERENCES auth.users ON DELETE CASCADE NOT NULL,
  word_id BIGINT REFERENCES words ON DELETE CASCADE NOT NULL,
  status learning_status DEFAULT 'new' NOT NULL,
  correct_count INTEGER DEFAULT 0 NOT NULL,
  incorrect_count INTEGER DEFAULT 0 NOT NULL,
  ease_factor FLOAT DEFAULT 2.5 NOT NULL,
  interval INTEGER DEFAULT 0 NOT NULL,
  next_review_date TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
  last_reviewed_at TIMESTAMP WITH TIME ZONE,
  is_favorite BOOLEAN DEFAULT FALSE NOT NULL,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
  UNIQUE(user_id, word_id)
);

-- サンプルデータの挿入 (5単語)
INSERT INTO words (word, meaning, pronunciation, part_of_speech, example_sentence, difficulty, category)
VALUES 
('apple', 'りんご', '/ˈæp.əl/', 'noun', 'I eat an apple every morning.', 'beginner', 'fruit'),
('book', '本', '/bʊk/', 'noun', 'She is reading an interesting book.', 'beginner', 'object'),
('cat', '猫', '/kæt/', 'noun', 'The cat is sleeping on the sofa.', 'beginner', 'animal'),
('dog', '犬', '/dɒɡ/', 'noun', 'He takes his dog for a walk.', 'beginner', 'animal'),
('elephant', '象', '/ˈel.ɪ.fənt/', 'noun', 'Elephants are the largest land animals.', 'beginner', 'animal');

-- RLS (Row Level Security) の設定
ALTER TABLE profiles ENABLE ROW LEVEL SECURITY;
ALTER TABLE user_word_progress ENABLE ROW LEVEL SECURITY;
ALTER TABLE words ENABLE ROW LEVEL SECURITY;

-- プロフィール: 自分のものだけ読み書き可能
CREATE POLICY "Users can view their own profile" ON profiles FOR SELECT USING (auth.uid() = id);
CREATE POLICY "Users can update their own profile" ON profiles FOR UPDATE USING (auth.uid() = id);

-- 学習進捗: 自分のものだけ読み書き可能
CREATE POLICY "Users can view their own progress" ON user_word_progress FOR SELECT USING (auth.uid() = user_id);
CREATE POLICY "Users can insert their own progress" ON user_word_progress FOR INSERT WITH CHECK (auth.uid() = user_id);
CREATE POLICY "Users can update their own progress" ON user_word_progress FOR UPDATE USING (auth.uid() = user_id);

-- 単語: 全員読み取り・更新可能 (プロトタイプ用)
DROP POLICY IF EXISTS "Words are viewable by everyone" ON words;
CREATE POLICY "Words are viewable by everyone" ON words FOR SELECT USING (true);

DROP POLICY IF EXISTS "Allow All Updates on Words" ON words;
CREATE POLICY "Allow All Updates on Words" ON words FOR UPDATE USING (true) WITH CHECK (true);

DROP POLICY IF EXISTS "Allow All Inserts on Words" ON words;
CREATE POLICY "Allow All Inserts on Words" ON words FOR INSERT WITH CHECK (true);

DROP POLICY IF EXISTS "Allow All Deletes on Words" ON words;
CREATE POLICY "Allow All Deletes on Words" ON words FOR DELETE USING (true);

-- Storage bucket for word images
INSERT INTO storage.buckets (id, name, public) VALUES ('word-images', 'word-images', true) ON CONFLICT DO NOTHING;

-- Allow public read access to images
DROP POLICY IF EXISTS "Public Access" ON storage.objects;
CREATE POLICY "Public Access" ON storage.objects FOR SELECT USING (bucket_id = 'word-images');

-- Allow anyone to upload/update images (プロトタイプ用)
DROP POLICY IF EXISTS "Allow All Uploads" ON storage.objects;
CREATE POLICY "Allow All Uploads" ON storage.objects FOR INSERT WITH CHECK (bucket_id = 'word-images');

DROP POLICY IF EXISTS "Allow All Updates" ON storage.objects;
CREATE POLICY "Allow All Updates" ON storage.objects FOR UPDATE USING (bucket_id = 'word-images');

