-- プロフィールテーブル (auth.usersと連携)
CREATE TABLE profiles (
  id UUID REFERENCES auth.users ON DELETE CASCADE PRIMARY KEY,
  full_name TEXT,
  avatar_url TEXT,
  role TEXT DEFAULT 'user' CHECK (role IN ('user', 'admin')),
  created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- 新規ユーザー作成時にプロフィールを自動作成する関数
CREATE OR REPLACE FUNCTION public.handle_new_user()
RETURNS trigger AS $$
BEGIN
  INSERT INTO public.profiles (id, full_name, avatar_url, role)
  VALUES (new.id, new.raw_user_meta_data->>'full_name', new.raw_user_meta_data->>'avatar_url', 'user');
  RETURN new;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

-- トリガーの設定
CREATE TRIGGER on_auth_user_created
  AFTER INSERT ON auth.users
  FOR EACH ROW EXECUTE FUNCTION public.handle_new_user();

-- 単語テーブル
DO $$ BEGIN
  CREATE TYPE difficulty_level AS ENUM ('beginner', 'intermediate', 'advanced');
EXCEPTION
  WHEN duplicate_object THEN null;
END $$;

CREATE TABLE words (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  word TEXT NOT NULL UNIQUE,
  meaning TEXT NOT NULL,
  pronunciation TEXT,
  part_of_speech TEXT,
  example_sentence TEXT,
  difficulty difficulty_level DEFAULT 'beginner' NOT NULL,
  category TEXT,
  image_url TEXT,
  audio_url TEXT,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- 学習進捗テーブル
DO $$ BEGIN
  CREATE TYPE learning_status AS ENUM ('new', 'learning', 'reviewing', 'mastered');
EXCEPTION
  WHEN duplicate_object THEN null;
END $$;

CREATE TABLE user_word_progress (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id UUID REFERENCES auth.users ON DELETE CASCADE NOT NULL,
  word_id BIGINT REFERENCES words ON DELETE CASCADE NOT NULL,
  status learning_status DEFAULT 'new' NOT NULL,
  correct_count INTEGER DEFAULT 0 NOT NULL,
  incorrect_count INTEGER DEFAULT 0 NOT NULL,
  ease_factor FLOAT DEFAULT 2.5 NOT NULL,
  interval INTEGER DEFAULT 0 NOT NULL,
  next_review_date TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
  last_reviewed_at TIMESTAMP WITH TIME ZONE,
  is_favorite BOOLEAN DEFAULT FALSE NOT NULL,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
  UNIQUE(user_id, word_id)
);

-- サンプルデータの挿入 (プロジェクト内の画像に対応した単語)
INSERT INTO words (word, meaning, pronunciation, part_of_speech, example_sentence, difficulty, category)
VALUES 
('abroad', '外国へ、海外で', '/əˈbrɔːd/', 'adv', 'I would like to study abroad next year.', 'intermediate', 'travel'),
('accommodation', '宿泊施設', '/əˌkɒm.əˈdeɪ.ʃən/', 'noun', 'We need to book accommodation for our trip.', 'intermediate', 'travel'),
('advertise', '広告する', '/ˈæd.və.taɪz/', 'verb', 'They decided to advertise their new product on TV.', 'intermediate', 'business'),
('agency', '代理店', '/ˈeɪ.dʒən.si/', 'noun', 'I contacted a travel agency to arrange my flight.', 'intermediate', 'business'),
('agreement', '合意、契約', '/əˈɡriː.mənt/', 'noun', 'Both parties signed the agreement.', 'intermediate', 'business'),
('agriculture', '農業', '/ˈæɡ.rɪ.kʌl.tʃər/', 'noun', 'The country depends heavily on agriculture.', 'advanced', 'general'),
('appliance', '電化製品', '/əˈplaɪ.əns/', 'noun', 'The kitchen is equipped with modern appliances.', 'intermediate', 'object'),
('appointment', '予約、約束', '/əˈpɔɪnt.mənt/', 'noun', 'I have a dentist appointment at 3 PM.', 'beginner', 'general'),
('arrival', '到着', '/əˈraɪ.vəl/', 'noun', 'Please wait in the arrival lounge.', 'beginner', 'travel'),
('atmosphere', '雰囲気、大気', '/ˈæt.mə.sfɪər/', 'noun', 'The restaurant has a very cozy atmosphere.', 'intermediate', 'general');

-- RLS (Row Level Security) の設定
ALTER TABLE profiles ENABLE ROW LEVEL SECURITY;
ALTER TABLE user_word_progress ENABLE ROW LEVEL SECURITY;
ALTER TABLE words ENABLE ROW LEVEL SECURITY;

-- プロフィール: 自分のものだけ読み書き可能
CREATE POLICY "Users can view their own profile" ON profiles FOR SELECT USING (auth.uid() = id);
CREATE POLICY "Users can update their own profile" ON profiles FOR UPDATE USING (auth.uid() = id);

-- 学習進捗: 自分のものだけ読み書き可能
CREATE POLICY "Users can view their own progress" ON user_word_progress FOR SELECT USING (auth.uid() = user_id);
CREATE POLICY "Users can insert their own progress" ON user_word_progress FOR INSERT WITH CHECK (auth.uid() = user_id);
CREATE POLICY "Users can update their own progress" ON user_word_progress FOR UPDATE USING (auth.uid() = user_id);

-- 単語: 全員読み取り・更新可能 (開発用)
DROP POLICY IF EXISTS "Words are viewable by everyone" ON words;
CREATE POLICY "Words are viewable by everyone" ON words FOR SELECT USING (true);

DROP POLICY IF EXISTS "Allow All Updates on Words" ON words;
CREATE POLICY "Allow All Updates on Words" ON words FOR UPDATE USING (true) WITH CHECK (true);

DROP POLICY IF EXISTS "Allow All Inserts on Words" ON words;
CREATE POLICY "Allow All Inserts on Words" ON words FOR INSERT WITH CHECK (true);

DROP POLICY IF EXISTS "Allow All Deletes on Words" ON words;
CREATE POLICY "Allow All Deletes on Words" ON words FOR DELETE USING (true);

-- Storage buckets
INSERT INTO storage.buckets (id, name, public) VALUES ('word-images', 'word-images', true) ON CONFLICT DO NOTHING;
INSERT INTO storage.buckets (id, name, public) VALUES ('word-audio', 'word-audio', true) ON CONFLICT DO NOTHING;

-- Allow public read access to storage
DROP POLICY IF EXISTS "Public Access" ON storage.objects;
CREATE POLICY "Public Access" ON storage.objects FOR SELECT USING (bucket_id IN ('word-images', 'word-audio'));

-- Allow anyone to upload/update (開発用)
DROP POLICY IF EXISTS "Allow All Uploads" ON storage.objects;
CREATE POLICY "Allow All Uploads" ON storage.objects FOR INSERT WITH CHECK (bucket_id IN ('word-images', 'word-audio'));

DROP POLICY IF EXISTS "Allow All Updates" ON storage.objects;
CREATE POLICY "Allow All Updates" ON storage.objects FOR UPDATE USING (bucket_id IN ('word-images', 'word-audio'));
